version: '3.3'
services:
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
  wordpress:
    image: wordpress:php7.4-fpm-alpine
    container_name: wordpress
    restart: always
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
    links:
      - mysql
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress
volumes:
      html: {}

